name = "Ayaan"

print(name[0:3])

print(name[-4:-1]) #IN NEGATIVE SLICING WORDS LIKH 0 TO GIVEN LIMIT USKE NEGATIVES LIKH -1 SE GIVEN TAK FIR 
# EG Q MEIN -4 KI JAGAH KA POSITIVE LIKH WHICH IS 1 SIMILARLY -1 KI JAGAH KA POSITIVE LIKH WHICH IS 4 (1:4)
print(name[1:4])
print(name[:5]) # _:x PEHLE KUCH NAHI DIYA TOH 0 (0:5)
print(name[0:]) # x:_ LAST MEIN KUCH NAHI DIYA TOH LAST LIMIT STRING KI (0:5)


