#USED TO DEFINE THE TYPE OF VARAIBLE 
a1 = 31.2
t1 = type(a1) # HERE THE VARAIABLE A CONSIST OF FLOATING POINT NO. SO IT SHOWS CLASS FLOAT
print (t1)

a2 = "Ayaan" 
t2 = type(a2) # HERE THE VARAIABLE B CONSIST OF STRING  SO IT SHOWS CLASS STR
print (t2)

a3 = "21.05" # DOUBLE QOUTE MEIN JO BHI LIKHA WOH STRING HI HOGA 
t3 = type(a3) # HERE THE VARAIABLE B CONSIST OF STRING  SO IT SHOWS CLASS STR
print (t3)

a4 = "21.05" # DOUBLE QOUTE MEIN JO BHI LIKHA WOH STRING HI HOGA 
b1 = float(a4) # THE VARIABLE A4 WILL CHANGE ITS TYPE TO FLOAT ONLY WHEN VALID
t4 = type(b1) # HERE THE VARAIABLE B CONSIST OF STRING  SO IT SHOWS CLASS STR
print (t4)

